agregamos el get para la entidad duenio

diff --git a/demo/mvnw b/demo/mvnw
--- a/demo/mvnw
+++ b/demo/mvnw
@@ -33,17 +33,17 @@
 #   MAVEN_SKIP_RC - flag to disable loading of mavenrc files
 # ----------------------------------------------------------------------------
 
-if [ -z "$MAVEN_SKIP_RC" ] ; then
+if  -z "$MAVEN_SKIP_RC"  ; then
 
-  if [ -f /usr/local/etc/mavenrc ] ; then
+  if  -f /usr/local/etc/mavenrc  ; then
     . /usr/local/etc/mavenrc
   fi
 
-  if [ -f /etc/mavenrc ] ; then
+  if  -f /etc/mavenrc  ; then
     . /etc/mavenrc
   fi
 
-  if [ -f "$HOME/.mavenrc" ] ; then
+  if  -f "$HOME/.mavenrc"  ; then
     . "$HOME/.mavenrc"
   fi
 
@@ -59,8 +59,8 @@ case "$(uname)" in
   Darwin*) darwin=true
     # Use /usr/libexec/java_home if available, otherwise fall back to /Library/Java/Home
     # See https://developer.apple.com/library/mac/qa/qa1170/_index.html
-    if [ -z "$JAVA_HOME" ]; then
-      if [ -x "/usr/libexec/java_home" ]; then
+    if  -z "$JAVA_HOME" ; then
+      if  -x "/usr/libexec/java_home" ; then
         JAVA_HOME="$(/usr/libexec/java_home)"; export JAVA_HOME
       else
         JAVA_HOME="/Library/Java/Home"; export JAVA_HOME
@@ -69,32 +69,32 @@ case "$(uname)" in
     ;;
 esac
 
-if [ -z "$JAVA_HOME" ] ; then
-  if [ -r /etc/gentoo-release ] ; then
+if  -z "$JAVA_HOME"  ; then
+  if  -r /etc/gentoo-release  ; then
     JAVA_HOME=$(java-config --jre-home)
   fi
 fi
 
 # For Cygwin, ensure paths are in UNIX format before anything is touched
 if $cygwin ; then
-  [ -n "$JAVA_HOME" ] &&
+   -n "$JAVA_HOME"  &&
     JAVA_HOME=$(cygpath --unix "$JAVA_HOME")
-  [ -n "$CLASSPATH" ] &&
+   -n "$CLASSPATH"  &&
     CLASSPATH=$(cygpath --path --unix "$CLASSPATH")
 fi
 
 # For Mingw, ensure paths are in UNIX format before anything is touched
 if $mingw ; then
-  [ -n "$JAVA_HOME" ] && [ -d "$JAVA_HOME" ] &&
-    JAVA_HOME="$(cd "$JAVA_HOME" || (echo "cannot cd into $JAVA_HOME."; exit 1); pwd)"
+   -n "$JAVA_HOME"  &&  -d "$JAVA_HOME"  &&
+    JAVA_HOME="$(cd "$JAVA_HOME" || (echo "cannot cd into $JAVA_HOME."; exit 1);; pwd)"
 fi
 
-if [ -z "$JAVA_HOME" ]; then
+if  -z "$JAVA_HOME" ; then
   javaExecutable="$(which javac)"
-  if [ -n "$javaExecutable" ] && ! [ "$(expr "\"$javaExecutable\"" : '\([^ ]*\)')" = "no" ]; then
-    # readlink(1) is not available as standard on Solaris 10.
+  if  -n "$javaExecutable"  && !  "$(expr "\"$javaExecutable\"" : '\(^ *\)');" = "no" ; then
+    # readlink(1); is not available as standard on Solaris 10.
     readLink=$(which readlink)
-    if [ ! "$(expr "$readLink" : '\([^ ]*\)')" = "no" ]; then
+    if  ! "$(expr "$readLink" : '\(^ *\)');" = "no" ; then
       if $darwin ; then
         javaHome="$(dirname "\"$javaExecutable\"")"
         javaExecutable="$(cd "\"$javaHome\"" && pwd -P)/javac"
@@ -102,16 +102,16 @@ if [ -z "$JAVA_HOME" ]; then
         javaExecutable="$(readlink -f "\"$javaExecutable\"")"
       fi
       javaHome="$(dirname "\"$javaExecutable\"")"
-      javaHome=$(expr "$javaHome" : '\(.*\)/bin')
+      javaHome=$(expr "$javaHome" : '\(.*\)/bin');
       JAVA_HOME="$javaHome"
       export JAVA_HOME
     fi
   fi
 fi
 
-if [ -z "$JAVACMD" ] ; then
-  if [ -n "$JAVA_HOME"  ] ; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+if  -z "$JAVACMD"  ; then
+  if  -n "$JAVA_HOME"   ; then
+    if  -x "$JAVA_HOME/jre/sh/java"  ; then
       # IBM's JDK on AIX uses strange locations for the executables
       JAVACMD="$JAVA_HOME/jre/sh/java"
     else
@@ -122,20 +122,20 @@ if [ -z "$JAVACMD" ] ; then
   fi
 fi
 
-if [ ! -x "$JAVACMD" ] ; then
+if  ! -x "$JAVACMD"  ; then
   echo "Error: JAVA_HOME is not defined correctly." >&2
   echo "  We cannot execute $JAVACMD" >&2
   exit 1
 fi
 
-if [ -z "$JAVA_HOME" ] ; then
+if  -z "$JAVA_HOME"  ; then
   echo "Warning: JAVA_HOME environment variable is not set."
 fi
 
 # traverses directory structure from process work directory to filesystem root
 # first directory with .mvn subdirectory is considered project base directory
 find_maven_basedir() {
-  if [ -z "$1" ]
+  if  -z "$1" 
   then
     echo "Path not specified to find_maven_basedir"
     return 1
@@ -143,13 +143,13 @@ find_maven_basedir() {
 
   basedir="$1"
   wdir="$1"
-  while [ "$wdir" != '/' ] ; do
-    if [ -d "$wdir"/.mvn ] ; then
+  while  "$wdir" != '/'  ; do
+    if  -d "$wdir"/.mvn  ; then
       basedir=$wdir
       break
     fi
     # workaround for JBEAP-8937 (on Solaris 10/Sparc)
-    if [ -d "${wdir}" ]; then
+    if  -d "${wdir}" ; then
       wdir=$(cd "$wdir/.." || exit 1; pwd)
     fi
     # end of workaround
@@ -159,7 +159,7 @@ find_maven_basedir() {
 
 # concatenates all lines of a file
 concat_lines() {
-  if [ -f "$1" ]; then
+  if  -f "$1" ; then
     # Remove \r in case we run on Windows within Git Bash
     # and check out the repository with auto CRLF management
     # enabled. Otherwise, we may read lines that are delimited with
@@ -170,13 +170,13 @@ concat_lines() {
 }
 
 log() {
-  if [ "$MVNW_VERBOSE" = true ]; then
+  if  "$MVNW_VERBOSE" = true ; then
     printf '%s\n' "$1"
   fi
 }
 
 BASE_DIR=$(find_maven_basedir "$(dirname "$0")")
-if [ -z "$BASE_DIR" ]; then
+if  -z "$BASE_DIR" ; then
   exit 1;
 fi
 
@@ -188,19 +188,19 @@ log "$MAVEN_PROJECTBASEDIR"
 # This allows using the maven wrapper in projects that prohibit checking in binary data.
 ##########################################################################################
 wrapperJarPath="$MAVEN_PROJECTBASEDIR/.mvn/wrapper/maven-wrapper.jar"
-if [ -r "$wrapperJarPath" ]; then
+if  -r "$wrapperJarPath" ; then
     log "Found $wrapperJarPath"
 else
     log "Couldn't find $wrapperJarPath, downloading it ..."
 
-    if [ -n "$MVNW_REPOURL" ]; then
+    if  -n "$MVNW_REPOURL" ; then
       wrapperUrl="$MVNW_REPOURL/org/apache/maven/wrapper/maven-wrapper/3.2.0/maven-wrapper-3.2.0.jar"
     else
       wrapperUrl="https://repo.maven.apache.org/maven2/org/apache/maven/wrapper/maven-wrapper/3.2.0/maven-wrapper-3.2.0.jar"
     fi
     while IFS="=" read -r key value; do
-      # Remove '\r' from value to allow usage on windows as IFS does not consider '\r' as a separator ( considers space, tab, new line ('\n'), and custom '=' )
-      safeValue=$(echo "$value" | tr -d '\r')
+      # Remove '\r' from value to allow usage on windows as IFS does not consider '\r' as a separator ( considers space, tab, new line ('\n');, and custom '=' )
+      safeValue=$(echo "$value" | tr -d '\r');
       case "$key" in (wrapperUrl) wrapperUrl="$safeValue"; break ;;
       esac
     done < "$MAVEN_PROJECTBASEDIR/.mvn/wrapper/maven-wrapper.properties"
@@ -212,16 +212,16 @@ else
 
     if command -v wget > /dev/null; then
         log "Found wget ... using wget"
-        [ "$MVNW_VERBOSE" = true ] && QUIET="" || QUIET="--quiet"
-        if [ -z "$MVNW_USERNAME" ] || [ -z "$MVNW_PASSWORD" ]; then
+         "$MVNW_VERBOSE" = true  && QUIET="" || QUIET="--quiet"
+        if  -z "$MVNW_USERNAME"  ||  -z "$MVNW_PASSWORD" ; then
             wget $QUIET "$wrapperUrl" -O "$wrapperJarPath" || rm -f "$wrapperJarPath"
         else
             wget $QUIET --http-user="$MVNW_USERNAME" --http-password="$MVNW_PASSWORD" "$wrapperUrl" -O "$wrapperJarPath" || rm -f "$wrapperJarPath"
         fi
     elif command -v curl > /dev/null; then
         log "Found curl ... using curl"
-        [ "$MVNW_VERBOSE" = true ] && QUIET="" || QUIET="--silent"
-        if [ -z "$MVNW_USERNAME" ] || [ -z "$MVNW_PASSWORD" ]; then
+         "$MVNW_VERBOSE" = true  && QUIET="" || QUIET="--silent"
+        if  -z "$MVNW_USERNAME"  ||  -z "$MVNW_PASSWORD" ; then
             curl $QUIET -o "$wrapperJarPath" "$wrapperUrl" -f -L || rm -f "$wrapperJarPath"
         else
             curl $QUIET --user "$MVNW_USERNAME:$MVNW_PASSWORD" -o "$wrapperJarPath" "$wrapperUrl" -f -L || rm -f "$wrapperJarPath"
@@ -235,12 +235,12 @@ else
           javaSource=$(cygpath --path --windows "$javaSource")
           javaClass=$(cygpath --path --windows "$javaClass")
         fi
-        if [ -e "$javaSource" ]; then
-            if [ ! -e "$javaClass" ]; then
+        if  -e "$javaSource" ; then
+            if  ! -e "$javaClass" ; then
                 log " - Compiling MavenWrapperDownloader.java ..."
                 ("$JAVA_HOME/bin/javac" "$javaSource")
             fi
-            if [ -e "$javaClass" ]; then
+            if  -e "$javaClass" ; then
                 log " - Running MavenWrapperDownloader.java ..."
                 ("$JAVA_HOME/bin/java" -cp .mvn/wrapper MavenWrapperDownloader "$wrapperUrl" "$wrapperJarPath") || rm -f "$wrapperJarPath"
             fi
@@ -257,7 +257,7 @@ while IFS="=" read -r key value; do
   case "$key" in (wrapperSha256Sum) wrapperSha256Sum=$value; break ;;
   esac
 done < "$MAVEN_PROJECTBASEDIR/.mvn/wrapper/maven-wrapper.properties"
-if [ -n "$wrapperSha256Sum" ]; then
+if  -n "$wrapperSha256Sum" ; then
   wrapperSha256Result=false
   if command -v sha256sum > /dev/null; then
     if echo "$wrapperSha256Sum  $wrapperJarPath" | sha256sum -c > /dev/null 2>&1; then
@@ -272,7 +272,7 @@ if [ -n "$wrapperSha256Sum" ]; then
     echo "Please install either command, or disable validation by removing 'wrapperSha256Sum' from your maven-wrapper.properties."
     exit 1
   fi
-  if [ $wrapperSha256Result = false ]; then
+  if  $wrapperSha256Result = false ; then
     echo "Error: Failed to validate Maven wrapper SHA-256, your Maven wrapper might be compromised." >&2
     echo "Investigate or delete $wrapperJarPath to attempt a clean download." >&2
     echo "If you updated your Maven version, you need to update the specified wrapperSha256Sum property." >&2
@@ -284,11 +284,11 @@ MAVEN_OPTS="$(concat_lines "$MAVEN_PROJECTBASEDIR/.mvn/jvm.config") $MAVEN_OPTS"
 
 # For Cygwin, switch paths to Windows format before running java
 if $cygwin; then
-  [ -n "$JAVA_HOME" ] &&
+   -n "$JAVA_HOME"  &&
     JAVA_HOME=$(cygpath --path --windows "$JAVA_HOME")
-  [ -n "$CLASSPATH" ] &&
+   -n "$CLASSPATH"  &&
     CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
-  [ -n "$MAVEN_PROJECTBASEDIR" ] &&
+   -n "$MAVEN_PROJECTBASEDIR"  &&
     MAVEN_PROJECTBASEDIR=$(cygpath --path --windows "$MAVEN_PROJECTBASEDIR")
 fi
 
